server:
  port: 8880 #服务注册中心端口号
spring:
  application:
    name: userManager-server
eureka:
  instance:
    hostname: localhost #服务注册中心实例的主机名
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}} # 在信息列表时显示的主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址(即左下角显示的信息是显示ip地址)
  client:
    serviceUrl:
          defaultZone: http://localhost:9003/eureka/  #服务注册中心的配置内容，指定服务注册中心的位置



